config/routes.rb
Quiz1::Application.routes.draw do
  root 'quiz1#index'
  resources :libraries

end

app/models/library.rb
class Library < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController

  def new
     @library = Library.new
  end

  def create
    Library.create(library_params)
    redirect_to root_path
  end

  def library_params
    params.require(:library).permit(:author, :title, :publisher, :variant)
  end


end

app/controllers/quiz1_controller.rb
class Quiz1Controller < ApplicationController
  def index
    @libraries = Library.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/quiz1_helper.rb
module Quiz1Helper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Library</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- <a class="navbar-brand" href="#">My Library</a> -->
        <%= link_to 'My Library', root_path, :class => 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <!-- <li class="active"><a href="#">Add Book <span class="sr-only">(current)</span></a></li>
          <li><a href="#">Link</a></li> -->
            <li> <%= link_to 'New Book', new_library_path %> </li>
          <!-- <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>  -->
        <!-- <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Link</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


<%= yield %>

</body>
</html>

app/views/libraries/new.html.erb
<!-- This is a new page for the form to show up. -->

<div class="booyah-box col-xs-10 col-xs-offset-1">
<h1> Enter book details</h1>
<%= simple_form_for @library do |f| %>
  <%= f.input :author %>
  <%= f.input :title %>
  <%= f.input :publisher %>
  <%= f.input :variant %>
  <br />
  <%= f.submit 'Create', :class => 'btn btn-primary' %>
  <% end %>
</div>

app/views/quiz1/index.html.erb
<!-- <center><h1> <%= @libraries.inspect %>         </h1></center> -->


<% @libraries.each do |library| %>
	<div class="transparent-box col-xs-10 col-xs-offset-1">
		<h1> <%= library.author %></h1>
		<h4> <%= library.title %> </h4>
		<h4> <%= library.publisher %></h4>
    <h4> <%= library.variant %> </h4>
	</div>

<% end %>